language: go
go:
  - 1.6
  - 1.7
  - tip
env:
  global:
    - test_dirs='./cmd/... ./irc/... ./sandstorm/... ./storage/...'
go_import_path: zenhack.net/go/irc-idler
install:
  - go get -t $test_dirs
  - go get ./vendor/github.com/Sirupsen/logrus
script:
  - go test -v $test_dirs
